export const GET_CUSTOMER_INFO_REQUEST = "GET_CUSTOMER_INFO_REQUEST";
export const GET_CUSTOMER_INFO_SUCCESS = "GET_CUSTOMER_INFO_SUCCESS";
export const GET_CUSTOMER_INFO_FAILURE = "GET_CUSTOMER_INFO_FAILURE";
